# Generated by Django 5.1.6 on 2025-02-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentdoctor',
            unique_together={('date_time_appointment', 'service_now', 'who_provides')},
        ),
    ]
